name: Gerando output
on:
  workflow_dispatch:
jobs:
  gerando_output:
    runs-on: ubuntu-latest
    outputs:
      output-shell: ${{ steps.exemplo-output.outputs.action_random }}
    steps:
      - name: Gerando Output com Shell
        id: exemplo-output
        run: |
          ACTION_RANDOM=$(( $RANDOM ))
          echo action_random=$ACTION_RANDOM >> $GITHUB_OUTPUT

      - name: Exibindo o output da action
        run: echo ${{ steps.exemplo-output.outputs.action_random }}
  exibindo-valores:
    runs-on: ubuntu-latest
    needs: gerando_output
    steps:
      - name: Exibindo os outputs do gerando_output
        run: |
          echo "Output shell: ${{ nneds.gerando_output.outputs.output-shell }}"